---
name: Continous Integration - Cron

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:

  secret:
    name: Call Secret Scanning
    uses: irishlab-io/admin/.github/workflows/reusable-secret.yml@main

    secrets: inherit

  pre-commit:
    name: Call Pre-Commit for private repo
    uses: irishlab-io/admin/.github/workflows/reusable-pre-commit.yml@main

    needs:
      - secret
